### ISSUE TITLE
2 issues I found

### ISSUE THREAD

**Issue by ffallah** [figment-networks/tezos-batch-payments#4]
Hi,
Thanks for your great work !
I found 2 issues :
1. you need to increase the fee to 1280 from 1110, my node was rejecting the transactions because of low fees.
2. If you dont run the script as root you will get a permission denied error :
`tezos-batch-payments.bash: line 316: 0: Permission denied`

**Comment by rfunduk** [comment]
Hey there, thanks for using tezos-batch-payments 😉 

We appreciate the feedback but unfortunately I think these are not problems with this project.

We run payouts every cycle and use a fee of 1110 ([here](https://tzscan.io/opMFchEcVEtEH35DDnG9EQ4KrdFYdTC3Wq2TLcKQTNC3KsgttCT) is our most recent payout). Perhaps your node is configured differently, and we could make the fee configurable or something, but I don't think a general increasing of the fee is something we want to do at this time.

For the permission denied error on line 316, I don't see how this is caused by not being root, and indeed we do not run, or recommend running, our script (or much of anything) as root. What version of `jq` do you have? Line 316 is just doing a very simple operation adding increasing counter values to the transactions.

**Comment by ffallah** [comment]
It is strange, when I used the default fee (1110), I got this error message in my node log:
`rejected by the mempool pre filter`
also if you check random transactions on tzscan.io almost all have 1.27mtz or 1.28mtz transaction fees. so it is default on the new tezos-client.
probably you are using an outdated tezos-node ?
Regarding the permission error, I was getting this error and switching to root resolved the issue.
my jq version is jq-1.5-1-a5b5cbe on debian 9
This is line 316 :
```
if [`expr $(echo -n $hex | wc -c) % 2` > 0 ]; then echo -n "0$hex"; else echo -n $hex; fi
```
I am also wondering how could this result in a permission denied error !
Could it be caused by line 314 or 315 ? 
```
unset hex; while read line; do hex+=$(echo -n $line | tr -d '/ \n'); done \
<<< $(dc -e "$dcr 16o0$(sed 's/./ 58*l&+/g' <<<$1)p")
```
is the backslash at the end of line 314 intentional ?

**Comment by rfunduk** [comment]
Ok so I added an option (`--fee`) to override the fee easily. Our node is not old, and it accepts 1110 fees, we've left the configs for that at the defaults I'm pretty sure 🤷‍♂ 

I was looking at the wrong version before about line 316, so yea I haven't a clue why `expr` or any other part of that would say permission denied... The backslash is definitely intentional. Try adding some debugging echos I guess? What OS/bash version are you on? Make sure you have the GNU versions of `dc` and `sed` and that they are relatively up to date.

**Comment by ffallah** [comment]
I found the problem about the permission denied issue.
It seems your script tries to write a filename called "0" in the working directory. because of my node security setup, the user whom I was running your script under, had no write access in tezos folder so the script generated a permission denied error.
I double checked on my node and confirmed there is a file called "0" created by your script in tezos directory.
```
-rw-r--r--  1 root  root         0 May  6 16:48 0
```
it is an empty file. it is created by root because I switched to root later to use your script.

**Comment by rfunduk** [comment]
So strange, I notice this `0` file on our servers as well. This code we're discussing was found somewhere online (Stackoverflow/etc) to do base58 decoding. I can't say I have good insight into the weeds of it and I can't explain why it's making that file... ah well, it sounds like you got it sorted and I don't think this is a critical issue for most people. If you're inclined to figure it out and adjust the base58 code we'd be happy to accept a pull request!

**Comment by ffallah** [comment]
Pull request submitted ;)
